### ISSUE TITLE
How to advertise a prefix with specified metric?

### ISSUE THREAD

**Issue by zhanleewo** [facebook/openr#20]
# Issue Description
I use breeze to advertise a prefix , but I want advertise a prefix with specified metric.
In our application scenarios, we should advertise some prefixes dynamically. We may advertise an identical prefix on different Open/R node since we want to offer our customers redundancy access service. So we want to set different metric to each identical prefix.

I did not find this feature in the Open/R's source code, Could you give me some guidance?
Or What do I need to do to implement it by myself if the OpenR doesn't include this feature?

**Comment by saifhhasan** [comment]
Hello @zhanleewo .. Open/R currently doesn't support setting up prefixes with metric values. You can advertise same prefix from two nodes, and traffic will be routed to nearest node (based on link cost, either hop-count or rtt or custom).

Since Open/R is link-state routing protocol, cost to prefixes corresponds to cost to reach the node which announced them.

You can influence path selection by setting custom link metric  (breeze lm set-link-metric ..)

**Comment by zhanleewo** [comment]
Ok, thank you @saifhhasan .
