### ISSUE TITLE
make error HealthChecker_types.h missing

### ISSUE THREAD

**Issue by ronm-jiffy** [facebook/openr#48]
# Issue Description
when making "e2e-image" on "terragraph.puma" make fail 
 openr/ig/gen-cpp2/HealthChecker_types.h: No such file or directory

# Environment
a PC
Yocto build environment

* OS version: 
ubuntu-18.04
...

# Minimal test code / Steps to reproduce the issue
terragraph.puma/build-x86$ bitbake e2e-image

# What's the actual result?
-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/OpenrCtrl.cpp.o -c thrift-out/openr/if/gen-cpp2/OpenrCtrl.cpp
| In file included from thrift-out/openr/if/gen-cpp2/OpenrCtrlAsyncClient.h:13,
|                  from thrift-out/openr/if/gen-cpp2/OpenrCtrl.h:14,
|                  from thrift-out/openr/if/gen-cpp2/OpenrCtrl.cpp:7:
| thrift-out/openr/if/gen-cpp2/OpenrCtrl_types.h:19:10: fatal error: openr/if/gen-cpp2/HealthChecker_types.h: No such file or directory
|  #include "openr/if/gen-cpp2/HealthChecker_types.h"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# What's the expected result?
build pass

**Comment by mcallahan** [comment]
Thanks for looking at terragraph.puma so quickly.

This looks like the terragraph.puma build silently failing on the thrift interface compiler rather than an OpenR bug.  I'll try to track down what's going on there when I get a chance.

Could you please checkout RELEASE_M40 on terragraph.puma and try a clean build?  It will help me determine if this is directly related to https://github.com/facebookexternal/terragraph.puma/commit/5162fc5a29d6b9523bfc32c2e25f8277c48b2768 and if so may unblock you.

**Comment by ronm-jiffy** [comment]
Hi, Thanks for quick reply
It seems like using branch M40_RELEASE produce some different issue. Am i doing something wrong?
attacked, console output

**Comment by ronm-jiffy** [comment]
Hi, 
After pulling new code the build is failing on a different file missing :)

`| In file included from thrift-out/openr/if/gen-cpp2/Decision_types.h:15,
|                  from thrift-out/openr/if/gen-cpp2/OpenrCtrl_types.h:16,
|                  from thrift-out/openr/if/gen-cpp2/OpenrCtrl_constants.h:11,
|                  from thrift-out/openr/if/gen-cpp2/OpenrCtrl_constants.cpp:8:
| thrift-out/openr/if/gen-cpp2/Fib_types.h:16:10: fatal error: openr/if/gen-cpp2/Lsdb_types.h: No such file or directory
|  #include "openr/if/gen-cpp2/Lsdb_types.h"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by mcallahan** [comment]
No, that's not you.  It's a brand new repository and we're still fixing things while we try to get ready for the availability of Qualcomm firmware to the OEMs.  I was mistaken about when I fixed the wireless-fw-interface dependency for e2e-image which turns out to be after RELEASE_M40.

I'll try to reproduce the original issue here to see what fbthrift is doing wrong.

**Comment by mcallahan** [comment]
I have not been able to reproduce this here yet.  The implication from your report is that the OpenR CMake dependencies are insufficient so the parallel make is trying to use files generated by thrift before thrift has completely generated them.

Mind adding this line to recipes-support/openr/openr_1.0.0.bb to serialize the compilation and give it another try?

PARALLEL_MAKE = ""

**Comment by ronm-jiffy** [comment]
Hi,
I tried adding the PARALLEL_MAKE="" flag and it did not help,
I also tried setting entire build process in parallel by setting PARALLEL_MAKE ?= ""  in 
terragraph.puma/build/conf/local.conf  (instead of PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count()}")

still missing file:
`| thrift-out/openr/if/gen-cpp2/Fib_types.h:16:10: fatal error: openr/if/gen-cpp2/Lsdb_types.h: No such file or directory
|  #include "openr/if/gen-cpp2/Lsdb_types.h"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Thanks

**Comment by mcallahan** [comment]
Fixed by 87811280c36818b783107ac9e6f1d5078ef3a380 in the terragraph.puma repository.

**Comment by ronm-jiffy** [comment]
Thank you!
It is looking good
